# Generated by Django 6.0.4 on 2026-05-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_avatar_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Foydalanuvchi'), ('employer', 'Ish beruvchi')], default='user', max_length=20),
        ),
    ]
