from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from jobs.models import Job, ConsultationRequest, Application
from blog.models import BlogPost
from users.models import Profile


class Command(BaseCommand):
    help = 'Seed sample jobs, blog posts, users, profile, and applications.'

    def handle(self, *args, **options):
        User = get_user_model()

        self.stdout.write(self.style.SUCCESS('Starting sample data seed...'))

        user_data = {
            'email': 'user@example.com',
            'username': 'sampleuser',
            'first_name': 'Sample',
            'last_name': 'User',
            'phone': '+998901234567',
        }

        user, created = User.objects.get_or_create(email=user_data['email'], defaults=user_data)
        if created:
            user.set_password('password123')
            user.save()
            self.stdout.write(self.style.SUCCESS('Created sample user: user@example.com / password123'))
        else:
            self.stdout.write(self.style.WARNING('Sample user already exists.'))

        profile, profile_created = Profile.objects.get_or_create(
            user=user,
            defaults={'experience': '5 yil xalqaro ish tajribasi, CV rekvizitlari yangilangan.'}
        )
        if profile_created:
            self.stdout.write(self.style.SUCCESS('Created profile for sample user.'))
        else:
            self.stdout.write(self.style.WARNING('Sample profile already exists.'))

        jobs = [
            {
                'title': 'Frontend dasturchi',
                'company': 'Global IT Solutions',
                'country': 'O‘zbekiston',
                'city': 'Toshkent',
                'address': 'Mustaqillik shoh ko‘chasi 12',
                'salary': '$900 - $1,200',
                'experience': '2-4 yil',
                'description': 'React, Vue yoki Angular bilan ishlash, REST API larni integratsiya qilish.',
                'featured': True,
            },
            {
                'title': 'Backend dasturchi (Python/Django)',
                'company': 'TechMove',
                'country': 'Qozog‘iston',
                'city': 'Almaty',
                'address': 'Astana prospekti 78',
                'salary': '$1,400 - $1,800',
                'experience': '3-5 yil',
                'description': 'Django asosida yechimlar yaratish, PostgreSQL va Docker bilan ishlash.',
                'featured': True,
            },
            {
                'title': 'Sotuv menejeri',
                'company': 'TradePro LLC',
                'country': 'Rossiya',
                'city': 'Moskva',
                'address': 'Tverskaya 16',
                'salary': '$1,000 - $1,300',
                'experience': '1-3 yil',
                'description': 'Xalqaro mijozlarni qidirish va takliflar tayyorlash.',
                'featured': False,
            },
            {
                'title': 'Graphic dizayner',
                'company': 'Creative Hub',
                'country': 'Tojikiston',
                'city': 'Dushanbe',
                'address': 'Rumi ko‘chasi 25',
                'salary': '$700 - $1,000',
                'experience': '1-2 yil',
                'description': 'Brend identifikatsiyasi va reklama materiallarini yaratish.',
                'featured': False,
            },
            {
                'title': 'Loyiha menejeri',
                'company': 'SmartProjects',
                'country': 'O‘zbekiston',
                'city': 'Samarqand',
                'address': 'Registon maydoni yaqinida',
                'salary': '$1,200 - $1,600',
                'experience': '4-6 yil',
                'description': 'IT va konsultatsiya loyihalarini boshqarish, jamoa bilan ishlash.',
                'featured': False,
            },
            {
                'title': 'DevOps muhandisi',
                'company': 'CloudTech',
                'country': 'Qozog‘iston',
                'city': 'Astana',
                'address': 'Qabanbay batyr ko‘chasi 45',
                'salary': '$1,600 - $2,200',
                'experience': '3-5 yil',
                'description': 'AWS, Kubernetes va CI/CD pipeline larni boshqarish.',
                'featured': True,
            },
            {
                'title': 'Marketing mutaxassisi',
                'company': 'BrandBoost',
                'country': 'Rossiya',
                'city': 'Sankt-Peterburg',
                'address': 'Nevskiy prospekt 88',
                'salary': '$800 - $1,100',
                'experience': '2-4 yil',
                'description': 'SMM kampaniyalari va brend strategiyalarini ishlab chiqish.',
                'featured': False,
            },
            {
                'title': 'Data analitik',
                'company': 'DataInsights',
                'country': 'O‘zbekiston',
                'city': 'Toshkent',
                'address': 'Amir Temur shoh ko‘chasi 5',
                'salary': '$1,000 - $1,400',
                'experience': '2-3 yil',
                'description': 'Python, SQL va Tableau bilan ma\'lumotlarni tahlil qilish.',
                'featured': False,
            },
            {
                'title': 'HR menejeri',
                'company': 'PeopleFirst',
                'country': 'Tojikiston',
                'city': 'Xorog',
                'address': 'Pamir ko‘chasi 12',
                'salary': '$600 - $900',
                'experience': '1-3 yil',
                'description': 'Kadrlar bilan ishlash, intervyu o‘tkazish va jamoa boshqaruvi.',
                'featured': False,
            },
            {
                'title': 'Mobile dasturchi (Flutter)',
                'company': 'AppMasters',
                'country': 'Qozog‘iston',
                'city': 'Shymkent',
                'address': 'Tauke khan ko‘chasi 33',
                'salary': '$1,200 - $1,600',
                'experience': '2-4 yil',
                'description': 'Flutter bilan cross-platform ilovalar yaratish.',
                'featured': True,
            },
            {
                'title': 'Quruvchi usta',
                'company': 'BuildPro',
                'country': 'O‘zbekiston',
                'city': 'Toshkent',
                'address': 'Navoiy ko‘chasi 100',
                'salary': '$500 - $800',
                'experience': '3-5 yil',
                'description': 'Turli xil qurilish ishlarini bajarish, beton quyish va devor qurish.',
                'featured': False,
            },
            {
                'title': 'Elektrik usta',
                'company': 'ElectroFix',
                'country': 'Qozog‘iston',
                'city': 'Almaty',
                'address': 'Abay ko‘chasi 50',
                'salary': '$600 - $900',
                'experience': '2-4 yil',
                'description': 'Elektr simlarini tortish, rozetka va chiroq o‘rnatish.',
                'featured': False,
            },
            {
                'title': 'Santexnik',
                'company': 'PlumbMaster',
                'country': 'Rossiya',
                'city': 'Moskva',
                'address': 'Leninskiy prospekt 25',
                'salary': '$700 - $1,000',
                'experience': '3-5 yil',
                'description': 'Suv va kanalizatsiya tizimlarini ta\'mirlash va o‘rnatish.',
                'featured': False,
            },
            {
                'title': 'Avtomobil mexanik',
                'company': 'AutoService',
                'country': 'Tojikiston',
                'city': 'Dushanbe',
                'address': 'Somoni ko‘chasi 15',
                'salary': '$400 - $700',
                'experience': '2-4 yil',
                'description': 'Avtomobillarni ta\'mirlash, dvigatel va transmissiya ishlar.',
                'featured': False,
            },
            {
                'title': 'Oshpaz',
                'company': 'TastyFoods',
                'country': 'O‘zbekiston',
                'city': 'Buxoro',
                'address': 'Ark ko‘chasi 8',
                'salary': '$300 - $600',
                'experience': '1-3 yil',
                'description': 'Milliy va xalqaro taomlar tayyorlash, restoran ishlar.',
                'featured': False,
            },
            {
                'title': 'Ofitsiant',
                'company': 'CafeCentral',
                'country': 'Qozog‘iston',
                'city': 'Astana',
                'address': 'Mangilik el ko‘chasi 20',
                'salary': '$250 - $400',
                'experience': 'Tajribasiz',
                'description': 'Mijozlarga xizmat ko‘rsatish, buyurtma qabul qilish.',
                'featured': False,
            },
            {
                'title': 'Buhgalter',
                'company': 'FinancePro',
                'country': 'Rossiya',
                'city': 'Sankt-Peterburg',
                'address': 'Gorokhovaya 10',
                'salary': '$800 - $1,200',
                'experience': '2-4 yil',
                'description': 'Moliyaviy hisobotlar, soliq va buxgalteriya ishlar.',
                'featured': False,
            },
            {
                'title': 'O‘qituvchi (Matematika)',
                'company': 'EduCenter',
                'country': 'Tojikiston',
                'city': 'Kulob',
                'address': 'Markaziy ko‘cha 5',
                'salary': '$400 - $700',
                'experience': '3-5 yil',
                'description': 'Maktabda matematika dars berish, o‘quvchilarga yordam.',
                'featured': False,
            },
            {
                'title': 'Hamshira',
                'company': 'HealthCare',
                'country': 'O‘zbekiston',
                'city': 'Samarqand',
                'address': 'Ibn Sino ko‘chasi 30',
                'salary': '$300 - $500',
                'experience': '1-3 yil',
                'description': 'Bemorlarga parvarish, dori berish va tibbiy yordam.',
                'featured': False,
            },
            {
                'title': 'Dori sotuvchi',
                'company': 'PharmaPlus',
                'country': 'Qozog‘iston',
                'city': 'Shymkent',
                'address': 'Respublika ko‘chasi 40',
                'salary': '$250 - $450',
                'experience': 'Tajribasiz',
                'description': 'Dorixona ishlar, mijozlarga maslahat berish.',
                'featured': False,
            },
            {
                'title': 'Sotuvchi',
                'company': 'ShopMart',
                'country': 'Rossiya',
                'city': 'Kazan',
                'address': 'Bauman ko‘chasi 12',
                'salary': '$300 - $500',
                'experience': 'Tajribasiz',
                'description': 'Do‘kon ishlar, mahsulot sotish va mijoz xizmat.',
                'featured': False,
            },
            {
                'title': 'Kassir',
                'company': 'SuperMarket',
                'country': 'Tojikiston',
                'city': 'Xorog',
                'address': 'Central ko‘cha 25',
                'salary': '$200 - $350',
                'experience': 'Tajribasiz',
                'description': 'Kassa ishlar, pul hisobi va mijoz xizmat.',
                'featured': False,
            },
            {
                'title': 'Haydovchi',
                'company': 'TransportCo',
                'country': 'O‘zbekiston',
                'city': 'Toshkent',
                'address': 'Yunusobod ko‘chasi 50',
                'salary': '$400 - $600',
                'experience': '2-4 yil',
                'description': 'Yuk tashish, shahar ichida haydash.',
                'featured': False,
            },
            {
                'title': 'Qorovul',
                'company': 'SecurityGuard',
                'country': 'Qozog‘iston',
                'city': 'Almaty',
                'address': 'Furmanov ko‘chasi 15',
                'salary': '$250 - $400',
                'experience': '1-3 yil',
                'description': 'Obyektni qorovullash, xavfsizlikni ta\'minlash.',
                'featured': False,
            },
            {
                'title': 'Tozalovchi',
                'company': 'CleanHouse',
                'country': 'Rossiya',
                'city': 'Moskva',
                'address': 'Tverskaya 50',
                'salary': '$200 - $350',
                'experience': 'Tajribasiz',
                'description': 'Ofis va uylarni tozalash, gigiena ishlar.',
                'featured': False,
            },
            {
                'title': 'Bog‘bon',
                'company': 'GreenGarden',
                'country': 'Tojikiston',
                'city': 'Dushanbe',
                'address': 'Rudaki ko‘chasi 30',
                'salary': '$250 - $400',
                'experience': '1-3 yil',
                'description': 'Bog‘ va park ishlar, o‘simliklarni parvarish qilish.',
                'featured': False,
            },
            {
                'title': 'Tikuvchi',
                'company': 'FashionTailor',
                'country': 'O‘zbekiston',
                'city': 'Andijon',
                'address': 'Navoiy ko‘chasi 20',
                'salary': '$300 - $500',
                'experience': '2-4 yil',
                'description': 'Kiyim tikish, ta\'mirlash va dizayn.',
                'featured': False,
            },
            {
                'title': 'Sartarosh',
                'company': 'BarberShop',
                'country': 'Qozog‘iston',
                'city': 'Astana',
                'address': 'Saryarka ko‘chasi 10',
                'salary': '$250 - $450',
                'experience': '1-3 yil',
                'description': 'Soch olish, soqol qirqish va parvarish.',
                'featured': False,
            },
            {
                'title': 'Fotograf',
                'company': 'PhotoStudio',
                'country': 'Rossiya',
                'city': 'Sankt-Peterburg',
                'address': 'Nevskiy 100',
                'salary': '$500 - $800',
                'experience': '2-4 yil',
                'description': 'Suratga olish, to‘y va tadbirlar.',
                'featured': False,
            },
            {
                'title': 'Musiqachi',
                'company': 'MusicBand',
                'country': 'Tojikiston',
                'city': 'Kulob',
                'address': 'Markaz 15',
                'salary': '$300 - $600',
                'experience': '3-5 yil',
                'description': 'Konsert va tadbirlar uchun musiqa ijro etish.',
                'featured': False,
            },
            {
                'title': 'Aktuar',
                'company': 'TheaterArt',
                'country': 'O‘zbekiston',
                'city': 'Toshkent',
                'address': 'Hamza ko‘chasi 25',
                'salary': '$400 - $700',
                'experience': '2-4 yil',
                'description': 'Teatr spektakllarida rol ijro etish.',
                'featured': False,
            },
            {
                'title': 'Jurnalist',
                'company': 'NewsAgency',
                'country': 'Qozog‘iston',
                'city': 'Almaty',
                'address': 'Abay 40',
                'salary': '$600 - $900',
                'experience': '3-5 yil',
                'description': 'Yangiliklar yozish, reportaj va intervyu.',
                'featured': False,
            },
            {
                'title': 'Tarjimon',
                'company': 'TranslatePro',
                'country': 'Rossiya',
                'city': 'Moskva',
                'address': 'Arbat 30',
                'salary': '$500 - $800',
                'experience': '2-4 yil',
                'description': 'Hujjat va matnlarni tarjima qilish.',
                'featured': False,
            },
            {
                'title': 'Psixolog',
                'company': 'MindCare',
                'country': 'Tojikiston',
                'city': 'Dushanbe',
                'address': 'Ismoili Somoni 50',
                'salary': '$400 - $700',
                'experience': '3-5 yil',
                'description': 'Maslahat berish, psixologik yordam.',
                'featured': False,
            },
            {
                'title': 'Veterinar',
                'company': 'PetHealth',
                'country': 'O‘zbekiston',
                'city': 'Namangan',
                'address': 'Istiqlol 20',
                'salary': '$300 - $600',
                'experience': '2-4 yil',
                'description': 'Hayvonlarga tibbiy yordam, emlash.',
                'featured': False,
            },
            {
                'title': 'Fermer',
                'company': 'AgroFarm',
                'country': 'Qozog‘iston',
                'city': 'Shymkent',
                'address': 'Agro ko‘chasi 10',
                'salary': '$350 - $550',
                'experience': '1-3 yil',
                'description': 'Dehqonchilik, ekin ekish va parvarish.',
                'featured': False,
            },
            {
                'title': 'Baliqchi',
                'company': 'FishCo',
                'country': 'Rossiya',
                'city': 'Vladivostok',
                'address': 'Morskoy 5',
                'salary': '$400 - $700',
                'experience': '2-4 yil',
                'description': 'Baliq ovlash va sotish.',
                'featured': False,
            },
            {
                'title': 'O‘rmonchi',
                'company': 'ForestGuard',
                'country': 'Tojikiston',
                'city': 'Xorog',
                'address': 'O‘rmon ko‘chasi 1',
                'salary': '$250 - $450',
                'experience': '1-3 yil',
                'description': 'O‘rmonni qorovullash, daraxt ekish.',
                'featured': False,
            },
            {
                'title': 'Geolog',
                'company': 'GeoExplore',
                'country': 'O‘zbekiston',
                'city': 'Toshkent',
                'address': 'Geologiya 15',
                'salary': '$700 - $1,100',
                'experience': '3-5 yil',
                'description': 'Yer qatlamlarini o‘rganish, tadqiqot.',
                'featured': False,
            },
            {
                'title': 'Arxeolog',
                'company': 'HistoryDig',
                'country': 'Qozog‘iston',
                'city': 'Taraz',
                'address': 'Tarix ko‘chasi 8',
                'salary': '$500 - $800',
                'experience': '4-6 yil',
                'description': 'Qadimiy yodgorliklarni qazish va o‘rganish.',
                'featured': False,
            },
            {
                'title': 'Meteorolog',
                'company': 'WeatherWatch',
                'country': 'Rossiya',
                'city': 'Moskva',
                'address': 'Pogoda 20',
                'salary': '$600 - $900',
                'experience': '3-5 yil',
                'description': 'Ob-havo prognozi, ma\'lumot yig‘ish.',
                'featured': False,
            },
            {
                'title': 'Ekolog',
                'company': 'EcoGuard',
                'country': 'Tojikiston',
                'city': 'Dushanbe',
                'address': 'Ekologiya 12',
                'salary': '$450 - $700',
                'experience': '2-4 yil',
                'description': 'Atrof-muhitni muhofaza qilish, monitoring.',
                'featured': False,
            },
            {
                'title': 'Iqtisodchi',
                'company': 'EconAnalysis',
                'country': 'O‘zbekiston',
                'city': 'Toshkent',
                'address': 'Iqtisod 25',
                'salary': '$800 - $1,200',
                'experience': '3-5 yil',
                'description': 'Iqtisodiy tahlil, prognoz va maslahat.',
                'featured': False,
            },
            {
                'title': 'Bankir',
                'company': 'BankPlus',
                'country': 'Qozog‘iston',
                'city': 'Almaty',
                'address': 'Bank ko‘chasi 30',
                'salary': '$900 - $1,300',
                'experience': '2-4 yil',
                'description': 'Kredit berish, mijoz xizmat.',
                'featured': False,
            },
            {
                'title': 'Sug‘urta agenti',
                'company': 'InsureSafe',
                'country': 'Rossiya',
                'city': 'Sankt-Peterburg',
                'address': 'Sug‘urta 40',
                'salary': '$500 - $800',
                'experience': '1-3 yil',
                'description': 'Sug‘urta polislarini sotish va maslahat.',
                'featured': False,
            },
            {
                'title': 'Turizm agenti',
                'company': 'TravelWorld',
                'country': 'Tojikiston',
                'city': 'Kulob',
                'address': 'Turizm 18',
                'salary': '$350 - $600',
                'experience': '2-4 yil',
                'description': 'Sayohat paketlarini tashkil etish.',
                'featured': False,
            },
            {
                'title': 'Sport murabbiyi',
                'company': 'FitClub',
                'country': 'O‘zbekiston',
                'city': 'Samarqand',
                'address': 'Sport 10',
                'salary': '$400 - $700',
                'experience': '3-5 yil',
                'description': 'Sportchilarga mashq berish.',
                'featured': False,
            },
            {
                'title': 'Mashinist',
                'company': 'RailWay',
                'country': 'Qozog‘iston',
                'city': 'Astana',
                'address': 'Temir yo‘l 5',
                'salary': '$600 - $900',
                'experience': '4-6 yil',
                'description': 'Poezd haydash va texnik xizmat.',
                'featured': False,
            },
            {
                'title': 'Pilot',
                'company': 'AirLines',
                'country': 'Rossiya',
                'city': 'Moskva',
                'address': 'Aeroport 1',
                'salary': '$2,000 - $3,000',
                'experience': '5-10 yil',
                'description': 'Samolyot haydash, xavfsizlik.',
                'featured': True,
            },
            {
                'title': 'Styuardessa',
                'company': 'SkyService',
                'country': 'Tojikiston',
                'city': 'Dushanbe',
                'address': 'Aeroport 2',
                'salary': '$400 - $700',
                'experience': '1-3 yil',
                'description': 'Parvozda mijoz xizmat.',
                'featured': False,
            },
            {
                'title': 'Kemachi',
                'company': 'SeaTransport',
                'country': 'O‘zbekiston',
                'city': 'Toshkent',
                'address': 'Daryo 15',
                'salary': '$500 - $800',
                'experience': '3-5 yil',
                'description': 'Kema haydash va yuk tashish.',
                'featured': False,
            },
            {
                'title': 'O‘qituvchi (Tarix)',
                'company': 'HistorySchool',
                'country': 'Qozog‘iston',
                'city': 'Shymkent',
                'address': 'Tarix 20',
                'salary': '$400 - $650',
                'experience': '3-5 yil',
                'description': 'Tarix dars berish.',
                'featured': False,
            },
            {
                'title': 'O‘qituvchi (Til)',
                'company': 'LanguageCenter',
                'country': 'Rossiya',
                'city': 'Kazan',
                'address': 'Til 25',
                'salary': '$450 - $700',
                'experience': '2-4 yil',
                'description': 'Chet til dars berish.',
                'featured': False,
            },
            {
                'title': 'O‘qituvchi (Fizika)',
                'company': 'ScienceLab',
                'country': 'Tojikiston',
                'city': 'Xorog',
                'address': 'Fizika 30',
                'salary': '$350 - $600',
                'experience': '3-5 yil',
                'description': 'Fizika dars berish va tajriba.',
                'featured': False,
            },
            {
                'title': 'Doktor',
                'company': 'MedCenter',
                'country': 'O‘zbekiston',
                'city': 'Buxoro',
                'address': 'Tibb 35',
                'salary': '$600 - $1,000',
                'experience': '4-6 yil',
                'description': 'Bemorlarni davolash.',
                'featured': False,
            },
            {
                'title': 'Farmatsevt',
                'company': 'DrugStore',
                'country': 'Qozog‘iston',
                'city': 'Taraz',
                'address': 'Dorixona 40',
                'salary': '$300 - $550',
                'experience': '1-3 yil',
                'description': 'Dori tavsiya qilish.',
                'featured': False,
            },
            {
                'title': 'Laborant',
                'company': 'LabTest',
                'country': 'Rossiya',
                'city': 'Vladivostok',
                'address': 'Lab 45',
                'salary': '$400 - $650',
                'experience': '2-4 yil',
                'description': 'Tahlil va testlar.',
                'featured': False,
            },
        ]

        for job_data in jobs:
            job, job_created = Job.objects.get_or_create(
                title=job_data['title'],
                company=job_data['company'],
                defaults=job_data,
            )
            if job_created:
                self.stdout.write(self.style.SUCCESS(f"Created job: {job.title}"))
            else:
                self.stdout.write(self.style.WARNING(f"Job already exists: {job.title}"))

        blog_posts = [
            {
                'title': '9 ta samarali CV yozish qoidasi',
                'content': 'CV dastlabki taassurotni beradi. To‘liq, aniq va professional yozing. Doim malakalarni ko‘rsatishni unutmang.',
                'image': None,
            },
            {
                'title': 'Intervyuga tayyorlanish bo‘yicha 5 maslahat',
                'content': 'Kompaniya haqida o‘rganing, ko‘zingizni ishonch bilan tuting, savollarga tayyor bo‘ling va o‘z kuchli tomonlaringizni aniq ifoda eting.',
                'image': None,
            },
            {
                'title': 'Xorijiy ish bozoriga chiqishning asosiy bosqichlari',
                'content': 'Hujjatlarni tayyorlash, til darajasini oshirish, malaka va diplomlarni tanishtirish hamda to‘g‘ri vakolatli agentliklarni topish muhim.',
                'image': None,
            },
            {
                'title': 'LinkedIn profilini qanday optimallashtirish kerak',
                'content': 'Professional rasm qo‘ying, tajribangizni batafsil yozing, tavsiyanomalarni to‘plang va faol bo‘ling.',
                'image': None,
            },
            {
                'title': 'Xorijda ish qidirishda til muammolari va yechimlari',
                'content': 'Til kurslariga yoziling, amaliy mashqlar qiling va intervyu uchun tayyorlaning.',
                'image': None,
            },
            {
                'title': 'Freelance ishlar orqali xalqaro tajriba orttirish',
                'content': 'Upwork va Freelancer kabi platformalarda ro‘yxatdan o‘ting, portfolio yarating va mijozlarni qidirib toping.',
                'image': None,
            },
            {
                'title': 'Ish joyida muvaffaqiyatli bo‘lish uchun 7 qoida',
                'content': 'Vaqtni to‘g‘ri boshqaring, jamoa bilan hamkorlik qiling, yangiliklarni o‘rganing va o‘z rivojlanishingizni unutmang.',
                'image': None,
            },
        ]

        for post_data in blog_posts:
            post, post_created = BlogPost.objects.get_or_create(
                title=post_data['title'],
                defaults=post_data,
            )
            if post_created:
                self.stdout.write(self.style.SUCCESS(f"Created blog post: {post.title}"))
            else:
                self.stdout.write(self.style.WARNING(f"Blog post already exists: {post.title}"))

        first_job = Job.objects.filter(featured=True).first()
        if first_job:
            app, app_created = Application.objects.get_or_create(
                user=user,
                job=first_job,
                defaults={'status': 'Pending'},
            )
            if app_created:
                self.stdout.write(self.style.SUCCESS(f"Created application for user: {first_job.title}"))
            else:
                self.stdout.write(self.style.WARNING('Sample application already exists.'))

        consultation, consultation_created = ConsultationRequest.objects.get_or_create(
            full_name='Aziz Ismoilov',
            phone='+998901112233',
            email='aziz.ismailov@example.com',
            defaults={
                'interested_country': 'Qozog‘iston',
                'profession': 'Frontend dasturchi',
                'message': 'Xorijda ish topish jarayoni bo‘yicha konsultatsiya kerak.',
            },
        )
        if consultation_created:
            self.stdout.write(self.style.SUCCESS('Created consultation request sample.'))
        else:
            self.stdout.write(self.style.WARNING('Sample consultation request already exists.'))

        self.stdout.write(self.style.SUCCESS('Sample data seed completed.'))
